---
language: android
jdk: oraclejdk8
android:
  components:
  - build-tools-22.0.1
  - doc-22
  - android-22
  - extra-android-m2repository
  - extra-android-support
script: "./gradlew assembleFossDebug JMPDCommAndroid:debugJavadoc JMPDCommAndroid:test
  JMPDCommJava:Build JMPDCommJava:javadoc JMPDCommJava:test"
